name: x divided by zero
description: This is an space for me discuss and spread my ideias. You are welcome to contribute here, in comments section. :P
url: http://diegoleite.me
baseurl: 

highlighter: pygments
comments: true
markdown: kramdown
exclude:
- node_modules

navigation:
- text: Blog
  url: /index.html
- text: About
  url: /about/index.html
