name: "x divided by zero"
description: # add some text here
url: http://diegoleite.me
baseurl: 

highlighter: pygments
comments: true
markdown: kramdown
exclude:
- node_modules

navigation:
- text: Blog
  url: /index.html
- text: About
  url: /about/index.html
